#!/bin/sh
#
# A pre-commit hook that checks if the staged C# files have been
# formatted using uncrustify.
# Add an identically named symlink in .git/hooks/ for the hook to work.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

uncrustify -c uncrustify.cfg --check $(git diff-index --cached --name-only --diff-filter=AM $against | grep '.cs$' | tr '\n' ' ')
